use jenkins slave sonar scan

diff --git a/Jenkinsfile-develop b/Jenkinsfile-develop
--- a/Jenkinsfile-develop
+++ b/Jenkinsfile-develop
@@ -134,6 +134,85 @@ def getChangeLog(pastBuilds) {
   return log;
 }
 
+def sonarQubeJenkinsNode () {
+  _openshift(env.STAGE_NAME, TOOLSPROJECT) {
+    node(sonarLabel) {
+        checkout scm
+        dir('sonar-runner') {
+          try {
+            // run scan
+            sh("oc extract secret/sonarqube-secrets --to=${env.WORKSPACE}/sonar-runner --confirm")
+            SONARQUBE_URL = sh(returnStdout: true, script: 'cat sonarqube-route-url')
+
+            sh "npm install typescript"
+            sh returnStdout: true, script: "./gradlew sonarqube -Dsonar.host.url=${SONARQUBE_URL} -Dsonar. -Dsonar.verbose=true --stacktrace --info"
+
+            // check if sonarqube passed
+            sh("oc extract secret/sonarqube-status-urls --to=${env.WORKSPACE}/sonar-runner --confirm")
+            SONARQUBE_STATUS_URL = sh(returnStdout: true, script: 'cat sonarqube-status-public')
+
+            boolean firstScan = false;
+            def OLD_SONAR_DATE
+            try {
+              // get old sonar report date
+              def OLD_SONAR_DATE_JSON = sh(returnStdout: true, script: "curl -w '%{http_code}' '${SONARQUBE_STATUS_URL}'")
+              OLD_SONAR_DATE = sonarGetDate (OLD_SONAR_DATE_JSON)
+            } catch (error) {
+              firstScan = true
+            }
+
+            if ( !firstScan ) {
+              // wiat for report to be updated
+              if ( !sonarqubeReportComplete ( OLD_SONAR_DATE, SONARQUBE_STATUS_URL ) ) {
+                echo "sonarqube report failed to complete, or timed out"
+
+                notifyRocketChat(
+                  "@all The latest build, ${env.BUILD_DISPLAY_NAME} of eagle-public seems to be broken. \n ${env.RUN_DISPLAY_URL}\n Error: \n sonarqube report failed to complete, or timed out : ${SONARQUBE_URL}",
+                  ROCKET_DEPLOY_WEBHOOK
+                )
+
+                currentBuild.result = "FAILURE"
+                exit 1
+              }
+            } else {
+              sleep (30)
+            }
+
+            SONARQUBE_STATUS_JSON = sh(returnStdout: true, script: "curl -w '%{http_code}' '${SONARQUBE_STATUS_URL}'")
+            SONARQUBE_STATUS = sonarGetStatus (SONARQUBE_STATUS_JSON)
+
+            // check if sonarqube passed
+            sh("oc extract secret/sonarqube-status-urls --to=${env.WORKSPACE}/sonar-runner --confirm")
+            SONARQUBE_STATUS_URL = sh(returnStdout: true, script: 'cat sonarqube-status-public')
+
+            if ( "${SONARQUBE_STATUS}" == "ERROR") {
+              echo "Scan Failed"
+
+              notifyRocketChat(
+                "@all The latest build ${env.BUILD_DISPLAY_NAME} of eagle-public seems to be broken. \n ${env.RUN_DISPLAY_URL}\n Error: \n ${error.message}",
+                ROCKET_DEPLOY_WEBHOOK
+              )
+
+              currentBuild.result = 'FAILURE'
+              exit 1
+            } else {
+              echo "Scan Passed"
+            }
+          } catch (error) {
+            notifyRocketChat(
+              "@all The latest build ${env.BUILD_DISPLAY_NAME} of eagle-public seems to be broken. \n ${env.BUILD_URL}\n Error: \n ${error.message}",
+              ROCKET_DEPLOY_WEBHOOK
+            )
+            throw error
+          } finally {
+            echo "Scan Complete"
+          }
+        }
+      }
+      return true;
+  }
+}
+
 def nodejsSonarqube () {
   _openshift(env.STAGE_NAME, TOOLSPROJECT) {
     String sonarLabel = "sonarqube-runner-${UUID.randomUUID().toString()}";
@@ -318,7 +397,7 @@ pipeline {
      steps {
        script {
          echo "Running Sonarqube"
-         def result = nodejsSonarqube()
+         def result = sonarQubeJenkinsNode()
        }
      }
     }
